version: "3.8"
services:

  app:
    build: .
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=development
      - FLASK_DEBUG=0
    command: flask run -h 0.0.0.0
